# Development Docker Compose
# Use this for local development with PostgreSQL container

services:
  # PostgreSQL Database (Development)
  postgres:
    image: postgres:16-alpine
    container_name: video_animation_postgres_dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: video_animation
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d video_animation"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (for cache and Celery)
  # Note: Comment out if using local Redis
  # redis:
  #   image: redis:7-alpine
  #   container_name: video_animation_redis_dev
  #   command: redis-server --appendonly yes
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-dev-data:/data
  #   restart: unless-stopped

volumes:
  postgres-dev-data:
  # redis-dev-data:
