"""add_video_showcase_table

Revision ID: 09496f4dab63
Revises: 0c12b9dcd989
Create Date: 2025-10-05 08:28:12.751976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09496f4dab63'
down_revision: Union[str, None] = '0c12b9dcd989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_showcases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False, comment='OSS video URL'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='Video generation prompt'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether to show on homepage'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Display order (higher first)'),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True, comment='Video thumbnail URL (optional)'),
    sa.Column('duration_seconds', sa.Integer(), nullable=True, comment='Video duration in seconds'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='View count'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_showcases_created_at'), 'video_showcases', ['created_at'], unique=False)
    op.create_index(op.f('ix_video_showcases_display_order'), 'video_showcases', ['display_order'], unique=False)
    op.create_index(op.f('ix_video_showcases_id'), 'video_showcases', ['id'], unique=False)
    op.create_index(op.f('ix_video_showcases_is_active'), 'video_showcases', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_showcases_is_active'), table_name='video_showcases')
    op.drop_index(op.f('ix_video_showcases_id'), table_name='video_showcases')
    op.drop_index(op.f('ix_video_showcases_display_order'), table_name='video_showcases')
    op.drop_index(op.f('ix_video_showcases_created_at'), table_name='video_showcases')
    op.drop_table('video_showcases')
    # ### end Alembic commands ###
